package com.prg3.mr_bid.model.entity;

public enum TypeProduct {
	
	FOOD, VEHICLES, TECHNOLOGY, APPLIANCES, SPORTSANDFRESHAIR,
	BEAUTY,PERSONALCARE, ACCESSORIESVEHICLES, WATCHES, JEWELRY,
	TOYS, BABIES, BOOKS, TOOLSANDINDUSTRIES, MUSICALINSTRUMENTS,
	REALESTATE, FASHION, TICKETS, CELLPHONES, COMPUTERS,
	OFFICE, SERVICES, OTHERS

}
