package com.prg3.mr_bid.controller;

public enum ControlCommands {

	SHOW_LOGIN,SHOW_HOME, SHOW_REGISTER_USER, SHOW_ADD_CREDIT_CARD,SHOW_MYCOUNT,SHOW_ADDPRODUCT,
	ACTION_LOGIN, ACTION_SINGIN,SHOW_PRODUCT;

}
